### ISSUE TITLE
Update for new nbconvert

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsmoke#45]
For nbconvert 6 (and jupyter_client, nbclient, etc)

**Comment by ceball** [comment]
See builds of #44 for example problems

**Comment by ceball** [comment]
Errors look like

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'session'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/nbclient/client.py", line 358, in _async_cleanup_kernel
    await ensure_async(self.km.cleanup_resources())
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/jupyter_client/manager.py", line 355, in cleanup_resources
    self.session.parent = None
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 548, in get
    value = self._validate(obj, default)
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 610, in _validate
    value = self.validate(obj, value)
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 1844, in validate
    self.error(obj, value)
  File "/home/travis/build/pyviz-dev/nbsmoke/.tox/py37/lib/python3.7/site-packages/traitlets/traitlets.py", line 690, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'session' trait of an AsyncKernelManager instance expected a Session, not the Session at '0x7fcc8a64dbe0'.```

**Comment by ceball** [comment]
#48 fixed
