### ISSUE TITLE
nbsmoke on Windows with Python 3.8

### ISSUE THREAD

**Issue by RomeshA** [pyviz-dev/nbsmoke#53]
Our tests just started failing with errors related to `asyncio`, I was thinking this might be due to nbsmoke having just been updated and saw you've already had some issues with Python 3.8 on Windows (e.g. https://github.com/pyviz-dev/nbsmoke/commit/eb0474eb06841da2255b138b35b1da3cfe56347d) - do you have any recommendations on how to proceed? Otherwise it was working before so I'll probably just hold nbsmoke back from 0.5...?

**Comment by ceball** [comment]
Thank you for your report.

> this might be due to nbsmoke having just been updated

I am fairly sure (though not certain) that your problem is unrelated to nbsmoke specifically, but is instead related to part(s) of the jupyter stack, tornado, and asyncio on windows with python 3.8.

You'd need to show the failures you're having for me to be sure. However, I can talk about the problem I had, which is likely the same one you're having.

> do you have any recommendations on how to proceed? Otherwise it was working before so I'll probably just hold nbsmoke back from 0.5...?

Short story: 

* **I believe you'll have the same problem with previous releases of nbsmoke** (e.g. 0.4.1), so holding back from 0.5 won't help. (Holding back from updating your environment _at all_ would help, though, since you had a working environment in the past.)

* **We need to figure out which dependency of nbsmoke is causing the problem**. Then go create (or find) an issue on that project about it being broken on python 3.8 on windows. In the meantime, either we can pin that dependency to an earlier version in nbsmoke (fixing it for all win/py38 users), or recommend users pin it themselves (so e.g. you yourself would need to pin it in your environment). The dependency in question might not be a top-level (i.e. explicitly stated) dependency, but some lower level (transitive) dependency. It might also not be one dependency we have to pin, but a group.

* **Do you have a record of packages in a previously working environment, which you could share**? That would help narrow down the search. Even dates of the most recent successful run vs first failure would be helpful (if your build environment is created fresh with up to date pypi packages each time). Usually I would use our windows build records for this, but unfortunately we don't have any; windows CI was deleted by my friendly but "windows does exist" teammates, and I only just restored it yesterday (which is how and when I discovered this problem...).

-----

Long story:

When it comes to running notebooks, nbsmoke is just a thin wrapper around standard jupyter components. That's good, because you want to be testing if your notebooks work with jupyter, since that's almost certainly how you're using them. However, there's a lot of churn in that stack (because it's actively developed, hence why you can keep getting new versions to work on new versions of python etc...). E.g. there have been multiple releases of various related jupyter projects over the last month. 

I don't use python 3.8 much at the moment, but - for example - here's what happens when I try to use the latest jupyter nbconvert on windows under python 3.8:

```
>jupyter nbconvert --execute Untitled.ipynb --to python
[NbConvertApp] Converting notebook Untitled.ipynb to python
Traceback (most recent call last):
  File "c:\users\sefkw\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\sefkw\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\sefkw\python38-32\scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\sefkw\python38-32\lib\site-packages\traitlets\config\application.py", line 837, in launch_instance
    app.start()
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\nbconvertapp.py", line 345, in start
    self.convert_notebooks()
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\nbconvertapp.py", line 519, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\nbconvertapp.py", line 484, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\nbconvertapp.py", line 413, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\exporters\exporter.py", line 182, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\exporters\exporter.py", line 200, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\exporters\templateexporter.py", line 367, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\exporters\exporter.py", line 144, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\exporters\exporter.py", line 319, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbconvert\preprocessors\execute.py", line 65, in preprocess
    self.execute()
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\sefkw\python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\client.py", line 519, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "c:\users\sefkw\python38-32\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\client.py", line 478, in async_setup_kernel
    await self.async_start_new_kernel_client()
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\client.py", line 403, in async_start_new_kernel_client
    await ensure_async(self.kc.start_channels())
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\client.py", line 106, in start_channels
    self.shell_channel.start()
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\client.py", line 151, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\connect.py", line 561, in connect_shell
    return self._create_connected_socket('shell', identity=identity)
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\sugar\context.py", line 226, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\_future.py", line 144, in __init__
    self._init_io_state()
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\asyncio\__init__.py", line 53, in _init_io_state
    self.io_loop.add_reader(self._fd, lambda : self._handle_events(0, 0))
  File "c:\users\sefkw\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\sefkw\python38-32\lib\site-packages\nbclient\client.py", line 360, in _async_cleanup_kernel
    await ensure_async(self.kc.stop_channels())
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\client.py", line 125, in stop_channels
    if self.shell_channel.is_alive():
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\client.py", line 151, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\connect.py", line 561, in connect_shell
    return self._create_connected_socket('shell', identity=identity)
  File "c:\users\sefkw\python38-32\lib\site-packages\jupyter_client\connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\sugar\context.py", line 226, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\_future.py", line 144, in __init__
    self._init_io_state()
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\asyncio\__init__.py", line 53, in _init_io_state
    self.io_loop.add_reader(self._fd, lambda : self._handle_events(0, 0))
  File "c:\users\sefkw\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
Exception ignored in: <function Socket.__del__ at 0x0416EA00>
Traceback (most recent call last):
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
    self.close()
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\_future.py", line 160, in close
    self._clear_io_state()
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\asyncio\__init__.py", line 60, in _clear_io_state
    self.io_loop.remove_reader(self._fd)
  File "c:\users\sefkw\python38-32\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored in: <function Socket.__del__ at 0x0416EA00>
Traceback (most recent call last):
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\_future.py", line 160, in close
  File "c:\users\sefkw\python38-32\lib\site-packages\zmq\asyncio\__init__.py", line 60, in _clear_io_state
  File "c:\users\sefkw\python38-32\lib\asyncio\events.py", line 504, in remove_reader
NotImplementedError:
```

That's the same issue as in nbsmoke.

The underlying issue is likely to be this, from https://github.com/tornadoweb/tornado/issues/2608:

> Python 3.8 asyncio is going to make the "proactor" event loop the default, instead of the current "selector" event loop. This is a problem for Tornado because the proactor event loop doesn't support the unix-style add_reader APIs that Tornado uses.
