### ISSUE TITLE
Cannot build a conda package on Python 3.8

### ISSUE THREAD

**Issue by maximlt** [pyviz-dev/nbsmoke#61]
I'm reporting this error here, although it might well be an error due to my lack of knowledge about the pyviz-dev tooling, or belong to another repository (e.g. pyctdev).

In the process of releasing nbsmoke I tried to the conda package with Python 3.8, i.e. by setting `PYTHON_VERSION` to `"3.8"` and `PKG_TEST_PYTHON` to `"--test-python=py38"` in `.github/workflows/build.yaml`. It failed with the following error:

```python
Leaving build/test directories:
  Work:
 /usr/share/miniconda3/envs/test/conda-bld/work 
  Test:
 /usr/share/miniconda3/envs/test/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /usr/share/miniconda3/envs/test/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:
source activate  /usr/share/miniconda3/envs/test/conda-bld/_build_env 


Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 451, in execute
    action(recipe, config)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 402, in test_action
    return api.test(recipe, move_broken=False, config=config)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/api.py", line 221, in test
    test_result = test(recipedir_or_package_or_metadata, config=config, move_broken=move_broken,
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/build.py", line 2862, in test
    actions = environ.get_install_actions(metadata.config.test_prefix,
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda_build/environ.py", line 801, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda/plan.py", line 466, in install_actions
    specs = tuple(MatchSpec(spec) for spec in specs)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda/plan.py", line 466, in <genexpr>
    specs = tuple(MatchSpec(spec) for spec in specs)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 48, in __call__
    parsed = _parse_spec_str(spec_arg)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/conda/models/match_spec.py", line 708, in _parse_spec_str
    if build is None and test_str[-1] != '*':
IndexError: string index out of range
TaskFailed - taskid:package_build
Command failed: 'conda build -c pyviz -c bokeh conda.recipe/ -t --append-file conda.recipe//recipe_append--py38-unit-default-pkg.yaml && conda build purge' returned 1
```

What happens there is that a yaml spec is generated by pyctdev with a requirement set to `python =` (without any version), which is malformed according to conda's spec and results in that error. That specific requirement (`python =`) is obtained by pyctdev here:
https://github.com/pyviz-dev/pyctdev/blob/d11c91aaa81c6034bdc42ce547823248acc05efb/pyctdev/util.py#L30

I haven't been able to find why this failed on Python 3.8 and not on Python 3.7 (I didn't spend too much time looking into that, being too happy that it finally worked!).

This issue can be closed in some months/years if the transition to building conda packages on 3.8 goes better than it did for me!

**Comment by maximlt** [comment]
Closing in favor of https://github.com/pyviz-dev/pyctdev/issues/95 that reports the issue appearing in pyctdev.
